/etc/budgie-desktop/defaults.list
/etc/profile.d/10-budgie-desktop-common.sh
/etc/profile.d/10-budgie-desktop.sh
/usr
distrologo/*.png  /usr/share/pixmaps
distrologo/*.svg  /usr/share/icons/hicolor/scalable/apps/
gdmcheck /usr/share/budgie-desktop/
home-folder /usr/share/budgie-desktop/
keycontrol /usr/share/budgie-desktop/
launch-welcome/launch_welcome /usr/share/budgie-desktop/
nemo-actions/*.nemo_action /usr/share/nemo/actions/
nemo-actions/*.sh /usr/share/nemo/actions/
onboard-autostart/* /etc/xdg/autostart/
xfce4-terminal/* /etc/xdg/xdg-budgie-desktop/xfce4/terminal
panel_override/* /usr/share/budgie-desktop/
raven_override/* /usr/share/budgie-desktop/raven/
schemas/25_budgie-desktop-environment.gschema.override /usr/share/glib-2.0/schemas
showdesktop /usr/share/budgie-desktop/
codename-wallpapers/ubuntu-budgie-codename-wallpapers.xml /usr/share/gnome-background-properties
codename-wallpapers/budgie-codename.png /usr/share/backgrounds/budgie/
budgie-control-center/* /usr/share/budgie-control-center/introduction/
crystal-dock/v2.16/crystal-dock/* /etc/xdg/crystal-dock-2.16/
crystal-dock/crystal-dock-autostart.desktop /etc/xdg/autostart