#!/bin/bash

gsettings set org.gnome.desktop.wm.keybindings show-desktop "['']"

# probably not required anymore
sleep 1

# Note -D is optional now, I've set the SYS_KEYS var to default to the same
#  directory in ./bin/gnome-custom-keybinding-setup.py
python3 ./bin/gnome-custom-keybinding-setup.py -D ./custom-keys.d/
