#!/bin/bash

gsettings set org.gnome.desktop.wm.keybindings show-desktop "['']"

#  directory in ./bin/gnome-custom-keybinding-setup.py
python3 ./bin/cleanup.py -D ./custom-keys.d/
python3 ./bin/gnome-custom-keybinding-setup.py -D ./custom-keys.d/
